project 'iosApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'mpplib', :path => '../mpplib'
  pod 'Toaster',"~> 2.3.0"
  pod 'Nuke', "9.2.2"

end
target 'iosAppTests' do
  inherit! :search_paths
  # Pods for testing
end
